<a href="https://colab.research.google.com/github/Allamsetti-Tulasi/AI-/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
my_list=[1,2,3,4,5]
arr=np.array(my_list)

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
#multinested aray
my_list=[1,2,3,4,5]
my_list1=[2,4,6,8,10]
my_list2=[3,6,9,12,15]
arr_new=np.array([my_list,my_list1,my_list2])
print(arr_new) 

In [6]:
arr_new[0:2,:]

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10]])

In [7]:
arr_new[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15]])

In [8]:
#arange function is used to give equally space values
arr=np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [9]:
np.linspace(0,9,20)

array([0.        , 0.47368421, 0.94736842, 1.42105263, 1.89473684,
       2.36842105, 2.84210526, 3.31578947, 3.78947368, 4.26315789,
       4.73684211, 5.21052632, 5.68421053, 6.15789474, 6.63157895,
       7.10526316, 7.57894737, 8.05263158, 8.52631579, 9.        ])

In [10]:
np.ones(4)

array([1., 1., 1., 1.])

In [18]:
np.ones((1,2),dtype=int)

array([[1, 1]])

In [20]:
np.random.rand(1,2)

array([[0.86138353, 0.76932319]])